version: 1.0.{build}
configuration: Release
platform: x64
image: Visual Studio 2017

before_build:
  - cmd: C:\Python36-x64\Scripts\pip install --upgrade pygount
  - cmd: C:\Python36-x64\Scripts\pygount libs -f summary -s cpp

build:
  project: PlusIrbis.2017.sln

after_build:
  - cmd: utils\doxygen

test_script: run_tests.cmd

artifacts:
  - path: x64
    name: Binaries
  - path: doxygen\html
    name: HtmlDocs
