set(HeaderFiles
    ../irbis/include/irbis_private.h
)

set(CppFiles
    ../irbis/src/AlphabetTable.cpp
    ../irbis/src/ByteNavigator.cpp
    ../irbis/src/ChunkedBuffer.cpp
    ../irbis/src/ClientQuery.cpp
    ../irbis/src/ClientSocket.cpp
    ../irbis/src/Connection.cpp
    ../irbis/src/ConnectionAdmin.cpp
    ../irbis/src/ConnectionBase.cpp
    ../irbis/src/ConnectionContext.cpp
    ../irbis/src/ConnectionFactory.cpp
    ../irbis/src/ConnectionFull.cpp
    ../irbis/src/ConnectionLite.cpp
    ../irbis/src/ConnectionPhantom.cpp
    ../irbis/src/ConnectionSearch.cpp
    ../irbis/src/DatabaseInfo.cpp
    ../irbis/src/Date.cpp
    ../irbis/src/DirectAccess.cpp
    ../irbis/src/Ean.cpp
    ../irbis/src/EmbeddedField.cpp
    ../irbis/src/Encoding.cp1251.cpp
    ../irbis/src/Encoding.cp866.cpp
    ../irbis/src/Encoding.cpp
    ../irbis/src/Encoding.koi8r.cpp
    ../irbis/src/Encoding.utf8.cpp
    ../irbis/src/Exemplar.cpp
    ../irbis/src/File.cpp
    ../irbis/src/FileSpecification.cpp
    ../irbis/src/GblResult.cpp
    ../irbis/src/IlfFile.cpp
    ../irbis/src/IniFile.cpp
    ../irbis/src/IO.cpp
    ../irbis/src/irbis.cpp
    ../irbis/src/Isbn.cpp
    ../irbis/src/Iso2709.cpp
    ../irbis/src/Lite.cpp
    ../irbis/src/MarcRecord.cpp
    ../irbis/src/MemoryChunk.cpp
    ../irbis/src/MenuEntry.cpp
    ../irbis/src/MenuFile.cpp
    ../irbis/src/MstControlRecord64.cpp
    ../irbis/src/MstDictionaryEntry64.cpp
    ../irbis/src/MstFile64.cpp
    ../irbis/src/MstRecord64.cpp
    ../irbis/src/MstRecordLeader64.cpp
    ../irbis/src/NumberChunk.cpp
    ../irbis/src/OptFile.cpp
    ../irbis/src/ParFile.cpp
    ../irbis/src/Phantom.cpp
    ../irbis/src/ProcessInfo.cpp
    ../irbis/src/RawRecord.cpp
    ../irbis/src/RecordField.cpp
    ../irbis/src/RecordSerializer.cpp
    ../irbis/src/Search.cpp
    ../irbis/src/ServerResponse.cpp
    ../irbis/src/ServerStat.cpp
    ../irbis/src/Span.cpp
    ../irbis/src/SubField.cpp
    ../irbis/src/Tcp4Socket.cpp
    ../irbis/src/TermInfo.cpp
    ../irbis/src/TermPosting.cpp
    ../irbis/src/Text.cpp
    ../irbis/src/TextNavigator.cpp
    ../irbis/src/TreeFile.cpp
    ../irbis/src/TreeNode.cpp
    ../irbis/src/Upc.cpp
    ../irbis/src/UserInfo.cpp
    ../irbis/src/Version.cpp
    ../irbis/src/XrfFile64.cpp
    ../irbis/src/XrfRecord64.cpp
)
