set(HeaderFiles
    ../../include/irbis_pft.h
    ../../include/irbis_direct.h
        ../irbis/include/irbis_internal.h
)

set(CppFiles
    ../irbis/src/Address.cpp
    ../irbis/src/AlphabetTable.cpp
    ../irbis/src/Author.cpp
    ../irbis/src/BookInfo.cpp
    ../irbis/src/ByteNavigator.cpp
    ../irbis/src/ChunkedBuffer.cpp
    ../irbis/src/ClientQuery.cpp
    ../irbis/src/ClientSocket.cpp
    ../irbis/src/Codes.cpp
    ../irbis/src/Connection.cpp
    ../irbis/src/ConnectionAdmin.cpp
    ../irbis/src/ConnectionBase.cpp
    ../irbis/src/ConnectionContext.cpp
    ../irbis/src/ConnectionFactory.cpp
    ../irbis/src/ConnectionFull.cpp
    ../irbis/src/ConnectionLite.cpp
    ../irbis/src/ConnectionPhantom.cpp
    ../irbis/src/ConnectionSearch.cpp
    ../irbis/src/DatabaseInfo.cpp
    ../irbis/src/Date.cpp
    ../irbis/src/DirectAccess.cpp
    ../irbis/src/Directory.cpp
    ../irbis/src/Ean.cpp
    ../irbis/src/EmbeddedField.cpp
    ../irbis/src/Encoding.cp1251.cpp
    ../irbis/src/Encoding.cp866.cpp
    ../irbis/src/Encoding.cpp
    ../irbis/src/Encoding.koi8r.cpp
    ../irbis/src/Encoding.utf8.cpp
    ../irbis/src/Exemplar.cpp
    ../irbis/src/File.cpp
    ../irbis/src/FileSpecification.cpp
    ../irbis/src/FoundLine.cpp
    ../irbis/src/Gbl.cpp
    ../irbis/src/IlfFile.cpp
    ../irbis/src/IniFile.cpp
    ../irbis/src/IO.cpp
    ../irbis/src/irbis.cpp
    ../irbis/src/Isbn.cpp
    ../irbis/src/Iso2709.cpp
    ../irbis/src/Lite.cpp
    ../irbis/src/Log.cpp
    ../irbis/src/MarcRecord.cpp
    ../irbis/src/MemoryPool.cpp
    ../irbis/src/Menu.cpp
    ../irbis/src/Mst.cpp
    ../irbis/src/NumberText.cpp
    ../irbis/src/OptFile.cpp
    ../irbis/src/ParFile.cpp
    ../irbis/src/Pft.cpp
    ../irbis/src/Phantom.cpp
    ../irbis/src/ProcessInfo.cpp
    ../irbis/src/RawRecord.cpp
    ../irbis/src/Reader.cpp
    ../irbis/src/RecordField.cpp
    ../irbis/src/RecordSerializer.cpp
    ../irbis/src/RecordStatus.cpp
    ../irbis/src/Registration.cpp
    ../irbis/src/Search.cpp
    ../irbis/src/ServerResponse.cpp
    ../irbis/src/ServerStat.cpp
    ../irbis/src/Span.cpp
    ../irbis/src/SubField.cpp
    ../irbis/src/Tcp4Socket.cpp
    ../irbis/src/TermInfo.cpp
    ../irbis/src/TermPosting.cpp
    ../irbis/src/Text.cpp
    ../irbis/src/TextNavigator.cpp
    ../irbis/src/Title.cpp
    ../irbis/src/TreeFile.cpp
    ../irbis/src/TreeNode.cpp
    ../irbis/src/Upc.cpp
    ../irbis/src/UserInfo.cpp
    ../irbis/src/Version.cpp
    ../irbis/src/Visit.cpp
    ../irbis/src/Xrf.cpp
)
